loginproject/appLogin/urls.py
from django.urls import include, re_path
from appLogin import views
# SET THE NAMESPACE!
app_name = 'appLogin'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^user_login/$',views.user_login,name='user_login'),
]

loginproject/loginproject/urls.py
from django.contrib import admin
from django.urls import include, re_path
from appLogin import views
urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^$',views.index,name='index'),
    re_path(r'^special/',views.special,name='special'),
    re_path(r'^applogin/',include('appLogin.urls')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
]

loginproject/appLogin/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProFilesInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

loginproject/appLogin/forms.py
from django import forms
from appLogin.models import UserProFilesInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields =('username','password','email')

class UserProFileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProFilesInfo
        fields = ('portfolio_site','profile_pic')

loginproject/appLogin/views.py
from django.shortcuts import render
from appLogin.forms import UserForm , UserProFileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'appLogin/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProFileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile= profile_form.save(commit = False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProFileInfoForm()
    return render(request,'appLogin/registration.html',{'user_form':user_form,
                                                        'profile_form':user_form,
                                                        'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("your account was inactive.")
        else:
            print("Someone tried to login and failed")
            print("Username:{} and Password:{}". format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request,'appLogin/login.html',{})

loginproject/templates/appLogin/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'appLogin:register' %}">Register</a></li>     
        
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'appLogin:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

loginproject/templates/appLogin/index.html
{% extends "appLogin/base.html" %}
{% block body_block %}
 <div class="container">
  <div class="jumbotron">
    <h1>Welcome !</h1>
  {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Go to the Register</h2>
    {% endif %}
  </div>
   
</div>
{% endblock %}

loginproject/templates/appLogin/login.html
{% extends 'appLogin/base.html' %}
{% block body_block %}
  
    <div class="jumbotron">
      <h1>Login here :</h1>
    <form method="post" action="{% url 'appLogin:user_login' %}">
        {% csrf_token %}
          
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><br>
            
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><br>
    <input type="submit" name="" value="Login">
    </form>
    </div>
    </div>
{% endblock %}

loginproject/templates/appLogin/registration.html
{% extends "appLogin/base.html" %}
{% load static %}
{% block body_block %}
 <!-- <div class="container"> --> 
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
         {% csrf_token %}
          {{ user_form.as_p }}
          
          <input type="submit" name="" value="Register">
        </form>
       {% endif %}
    </div>
  </div>
{% endblock %}